### ISSUE TITLE
Error decoding string to json

### ISSUE THREAD

**Issue by antonybenhur** [ShabbirHasan1/kiteconnect-data-structures#1]
Hi Shabbir, Thanks for this wonderful code. Whenever I try to execute the python version for ticker full as json string. I get an error as "json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 13 (char 14)". Appreciate if you can look into this. Thanks.

**Comment by antonybenhur** [comment]
> 

My apologies as I chose the wrong file. Now it reads but the ticker_full_from_dict throws an error ' assert isinstance(x, list)
AssertionError'

**Comment by ShabbirHasan1** [comment]
> > 
> 
> My apologies as I chose the wrong file. Now it reads but the ticker_full_from_dict throws an error ' assert isinstance(x, list) AssertionError'

The latest commits / changes from the [kiteconnect-mocks @ cbfd4c8](https://github.com/zerodha/kiteconnect-mocks) has been incorporated, which has resolved the issue.

Please check your program again or refer this [gist](https://gist.github.com/ShabbirHasan1/f34137cc75cd7d8334b95193e409e234)
